version: '3'

services:
  # app:
  #   build: .
  #   working_dir: /app
  #   network_mode: host
  #   command: npm start
  #   volumes:
  #     - .:/app

  mongo:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: local-devices

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/